name: aws-s3
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install-aws-cli
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1

      - name: aws version check    
        run: aws --version
        shell: bash 

      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          ls -ltr
          pwd
