name: Clone Repository

on:
  push:
    branches:
      - test  # Adjust the branch name if needed

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: GudditiNaganjaneyulu/RIkoouu  # Repository to clone
          token: ${{ secrets.ACCESS_TOKEN }}  # Access token stored as a secret

      - name: npm install
        run: |
          ls -lrt        
          npm install --no-save

      - name: Save npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: v1-infra-npm-${{ hashFiles('package-lock.json') }}
