name: docker test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Build and test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
          docker run -t --rm $LOCAL_IMAGE_TEST npm run coverage

      
