name: docker-output-test
on: [push]

env:
  user: "gudditi"
  image: "chat"
  tag: "latest"

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: docker build
        run: |
          DOCKER_IMAGE=${{ env.user }}/${{ env.image }}:${{ env.tag }}
          docker build -t $DOCKER_IMAGE .
          echo "test=$DOCKER_IMAGE" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
