name: Install Infra

on:
  push:
    branches:
      - test

jobs:
  install_infra:
    runs-on: ubuntu-latest

    steps:
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: v1-infra-npm-${{ hashFiles('package-lock.json') }}

      - name: npm install
        run: npm install --no-save

      - name: Save npm cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: v1-infra-npm-${{ hashFiles('package-lock.json') }}
