name: docker test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"

jobs:
  docker-build:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        id: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
          echo "image=$LOCAL_IMAGE_TEST" >> $GITHUB_OUTPUT

  second-job:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Use prior output
        run: echo "The count was ${{ steps.stepid.outputs.image }}"

      - name: Slack Notification

        uses: rtCamp/action-slack-notify@v2

        env:

          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
