name: Outputs -testing
on: [push]
env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: docker nuild
        run: |  
          export LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
        
      - id: step1
        run: echo "test=$LOCAL_IMAGE_TEST" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
