name: docker test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"
  LOCAL_IMAGE_NAME: ""

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        id: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
      - name: Save value to environment file
        run: echo "LOCAL_IMAGE=$LOCAL_IMAGE_TEST" >> $GITHUB_ENV




  print-image-name:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name:
        run: echo "------------------------------"
      - name: Read exported value
        run: |
          echo "The exported value is $LOCAL_IMAGE"
