name: docker test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      local-image-test: ${{ steps.build.outputs.LOCAL_IMAGE_TEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        id: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: local-image-test
          path: ${{ steps.build.outputs.LOCAL_IMAGE_TEST }}

  another-job:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: local-image-test
          path: ${{ github.workspace }}/artifact

      - name: Set input variable
        run: echo "::set-env name=LOCAL_IMAGE_TEST::${{ env.GITHUB_WORKSPACE }}/artifact/${{ env.IMAGE_NAME }}"

      - name: Print output value
        run: echo $LOCAL_IMAGE_TEST
