name: docker test
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Build and test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
          docker run -t --rm $LOCAL_IMAGE_TEST npm run coverage
          echo "IMAGE=$LOCAL_IMAGE_TEST" >> $GITHUB_ENV
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $IMAGE
  
          

      
