name: docker images build

on:

  push:

    branches:

      - main

      - 'testing/*'

      - 'staging/*'

      - 'production/*'

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node-version: [18.15]

    steps:

      - name: Checkout

        uses: actions/checkout@v2
      - name: Build and test
        if: ${{ parameters.test }}
        run: |
          LOCAL_IMAGE_TEST=${{ env.IMAGE_NAME }}-test:${{ github.sha }}
          docker build -t $LOCAL_IMAGE_TEST .

