name: testing
on: [push]
env:
   IMAGE_NAME: "chat"
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - name: Build and test
        id: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
      - id: step1
        run: echo "test=$LOCAL_IMAGE_TEST" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}

        run: echo "$OUTPUT1"
