name: docker test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REGION: us-east-1
  ECR_REPOSITORY_NAME: "chat"
  IMAGE_NAME: "chat"
  LOCAL_IMAGE_NAME: ""

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        id: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          export LOCAL_IMAGE_TEST=$IMAGE_NAME-test:$GITHUB_SHA
          docker build -t $LOCAL_IMAGE_TEST .
          echo "$LOCAL_IMAGE_TEST"


  print-image-name:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Print image name
        run: |
          # Retrieve the value from workflow state
          local_image_test_state=$(echo "${{ github.event.workflow_run.outputs.local_image_test }}")

          # Print the value from workflow state
          echo "The image name from state is $local_image_test_state"

          # Retrieve the value from output
          local_image_test_output=$(echo "${{ needs.docker-build.outputs.local_image_test }}")

          # Print the value from output
          echo "The image name from output is $local_image_test_output"
