name: branching
on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  branching:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Deployment Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "::set-output name=env::dev"
          elif [[ "${{ github.ref }}" == "refs/heads/testing/"* ]]; then
            echo "::set-output name=env::qa"
          fi

      - name: cdk diff
        run: echo "${{ steps.set-env.outputs.env }}"
