name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2



      - name: Set environment variable based on branch name
        run: |
          if [[ ${{ env.BRANCH_NAME }} == "develop" ]]; then
            echo "env=dev" >> $GITHUB_ENV
          elif [[ ${{ env.BRANCH_NAME }} == "testing/"* ]]; then
            echo "env=qa" >> $GITHUB_ENV
          elif [[ ${{ env.BRANCH_NAME }} == "main" ]]; then
            echo "env=main" >> $GITHUB_ENV
          else
            echo "Unknown branch"
            exit 1
          fi

      - name: Print branch name and environment
        run: |
          echo "Branch: ${{ env.BRANCH_NAME }}"
          echo "Environment: ${{ env.env }}"

      # Additional steps for the build process

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cleanup
        run: |
          echo "Perform cleanup here"

      # Additional cleanup steps

