name: Print Branch Name

on:
  push:
    branches:
      - dev
      - main

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Print branch name
        run: echo "Branch: ${{ github.ref }}"
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
