name: Print Branch Name

on:
  push:
    branches:
      - dev
      - main

jobs:
  print-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Branch Names
        uses: tj-actions/branch-names@v7.0.1

