name: Manual Approval Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval
        id: approval
        if: github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.TOKEN }}
          title: Manual Approval
          body: Please review and approve the changes

      - name: Deploy
        if: needs.approval.result == 'approved'
        run: |
          echo "Deploying..."

  hello:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: |
          echo "Hello, World!"
