name: Hello World Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          # Add your build and test commands here

      - name: Request approval
        id: approval
        uses: appleboy/approval@v0.0.1
        with:
          keyword: "true"

      - name: Send notification
        if: steps.approval.outputs.approved == 'true'
        run: |
          # Add your notification command here

      - name: Deploy
        if: steps.approval.outputs.approved == 'true'
        run: |
          # Add your deployment command here

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Add your test commands here

      - name: Request approval
        id: test-approval
        uses: appleboy/approval@v0.0.1
        with:
          keyword: "true"

      - name: Send test results
        if: steps.test-approval.outputs.approved == 'true'
        run: |
          # Add your test result notification command here
