name: Hello World Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          # Add your build and test commands here
          echo "hello world"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Approve with keyword
        if: ${{ github.event.inputs.approval == 'true' }}
        run: echo "Workflow approved with keyword 'true'"
        
      - name: echo
        run: echo "running"
