name: Hello World Workflow

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approve with keyword "true"'
        required: false

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Approve with keyword
        if: ${{ github.event.inputs.approval == 'true' }}
        run: echo "Workflow approved with keyword 'true'"

      - name: Approve with icon click
        if: ${{ github.event_name == 'workflow_dispatch' && !github.event.inputs.approval }}
        run: echo "Workflow approved by clicking the icon"
