name: Hello World Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          # Add your build and test commands here
          echo "hello world"

  test:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.approval == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prompt for approval
        id: approval
        run: |
          echo "Do you want to approve the workflow? Enter 'true' to approve."
          echo "::set-output name=approval::${{ steps.approval.outputs.approval }}"

      - name: Approve with keyword
        if: steps.approval.outputs.approval == 'true'
        run: echo "Workflow approved with keyword 'true'"
        
      - name: echo
        run: echo "running"
