name: Build and Deploy

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15]
    steps:

      - name: Checkout infra repository
        uses: actions/checkout@v2

      - name: Clone RIkoouu repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global http.extraheader "Authorization: Bearer $ACCESS_TOKEN"
          git clone https://github.com/GudditiNaganjaneyulu/RIkoouu
