name: Manual Approval Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "This is step 1"

      - name: Manual Approval Step
        id: manual_approval
        run: echo "This step requires manual approval"
        if: ${{ needs.approval.outputs.approve == 'true' }}

      - name: Step 3
        run: echo "This is step 3"

  approval:
    runs-on: ubuntu-latest
    outputs:
      approve: ${{ steps.approve.outputs.approve }}

    steps:
      - name: Manual Approval
        id: approve
        run: echo "::set-output name=approve::true"
        if: github.event_name == 'pull_request'
