name: Build and Deploy

on:
  push:
    branches:
      - main
      - 'testing/*'
      - 'staging/*'
      - 'production/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15]
    steps:

      - name: Checkout infra repository
        uses: actions/checkout@v2

      - name: Clone RIkoouu repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global http.https://github.com/.extraheader "Authorization: Bearer $ACCESS_TOKEN"
          git clone https://GudditiNaganjaneyulu:${ACCESS_TOKEN}@github.com/GudditiNaganjaneyulu/RIkoouu.git
          git config --global --unset http.https://github.com/.extraheader
          git config --global credential.helper "store --file=.git/credentials"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
