name: Build and Deploy

on:
  push:
    branches:
      - main
      - 'testing/*'
      - 'staging/*'
      - 'production/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.15]

    - name: Checkout infra repository
      uses: actions/checkout@v2
      with:
        repository: GudditiNaganjaneyulu/RIkoouu
        token: ${{ secrets.GITHUB_TOKEN }}

