name: Clone Repository

on:
  push:
    branches:
      - test

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: GudditiNaganjaneyulu/RIkoouu
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: List Repository Contents
        run: ls -la
