name: Docker Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t gudditi/image .

      - name: Manual Approval
        id: approval
        run: echo "::set-output name=approve::true"
        if: github.event_name == 'pull_request'

      - name: Push Docker image
        run: docker push gudditi/image
        if: ${{ needs.build.outputs.approve == 'true' }}
