on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
    - uses: vuiggigc iffuufffufuchjv

    - name: Slack Notification

      uses: rtCamp/action-slack-notify@v2


      env:

        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Slack Notification

      uses: rtCamp/action-slack-notify@v2

      env:

        SLACK_CHANNEL: general

        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'

        SLACK_ICON: https://github.com/rtCamp.png?size=48

        SLACK_MESSAGE: 'Post Content :rocket:'

        SLACK_TITLE: Post Title

        SLACK_USERNAME: rtCamp

        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: run 
      run: bing ong
        

