name: branch test

on: [push]

jobs:
  branch-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        run: |
          echo "GITHUB_REF_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
