name: Build and Test

on:

  push:

    branches:

      - main

      - 'testing/*'

      - 'staging/*'

      - 'production/*'

  workflow_dispatch:

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Set up Node.js

        uses: actions/setup-node@v2

        with:

          node-version: ${{ matrix.node-version }}

      - name: Install dependencies

        run: npm ci

      - name: Build

        run: npm run build

      - name: Test

        run: npm test

