name: Fetch Repository

on:
  push:
    branches:
      - test

jobs:
  fetch-repo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Checkout private repository
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git clone ${{ secrets.REPO_URL }}t  # Replace with the SSH URL of your private repository

      # Add additional steps or actions here to work with the repositories
