name: Your Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Build step"

  manual-approval:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Manual Approval Step
        run: echo "Manual approval required"

  deploy:
    needs: manual-approval
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: echo "Deploy step"
