name: Fetch Repository

on:
  push:
    branches:
      - test

jobs:
  fetch-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_TOKEN}}
          repository: GudditiOrg/NodeJs-Docker-APP



      # Add additional steps or actions here to work with the repositories
